### ISSUE TITLE
Bulk Update throws error.

### ISSUE THREAD

**Issue by malabya** [larowlan/pathauto#3]
When I try to bulk update aliases, throws an ajax error.

An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /batch?id=3&op=do_nojs&op=do
StatusText: Internal Server Error
ResponseText: 

Using beta-15.

**Comment by larowlan** [comment]
This repo is superceded
Please see http://github.com/md-systems/pathauto
