### ISSUE TITLE
Create menu item with parent item

### ISSUE THREAD

**Issue by msn1987** [larowlan/pathauto#5]
Hi, I honestly don't know where to report a possible bug, on the Drupal pages I have read to write them on Github, and over here I don't see anybody doing that ;) Still, here it is. If this is not the correct way, please tell me so next time I can do it like it should done.
## 

Drupal: 8.1.0
Pathauto: 8.x-1.0-alpha2
Ctools: 8.x-3.0-alpha25

When publishing a new node and setting up "Provide a menu link" , selecting a parent-item and checking "Generate automatic URL alias", the generated path does not include the URL slug of the parent. After editing the node and publishing it again, it does so. I use the URL pattern below.

`[node:menu-link:parents:join-path]/[node:title]`

I guess when publishing it for the first time, Drupal/Pathauto does not yet know that the node is a childpage. After publishing it for the first time, it does.

Again, please tell me if this is the right way to report "bugs".

Kind regards,
msn

**Comment by Berdir** [comment]
Looks like you found the wrong instructions. pathauto is on drupal.org now, issues should be reported there. There are existing issues for this problem, and @larowlan is working on a solution.

**Comment by larowlan** [comment]
https://www.drupal.org/node/2670120 is the existing issue w/ a working patch - needs review
